///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexPOC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ContactUs recording.
    /// </summary>
    [TestModule("ab4e3069-16f4-468f-8f6b-1cbec6b39402", ModuleType.Recording, 1)]
    public partial class ContactUs : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexPOCRepository repository.
        /// </summary>
        public static RanorexPOCRepository repo = RanorexPOCRepository.Instance;

        static ContactUs instance = new ContactUs();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ContactUs()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ContactUs Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.planittesting.com' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://www.planittesting.com", "chrome", "", false, false, false, false, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PlanitSoftwareTestingDigitalSolut.ContactUs' at 32;10.", repo.PlanitSoftwareTestingDigitalSolut.ContactUsInfo, new RecordItemIndex(1));
            repo.PlanitSoftwareTestingDigitalSolut.ContactUs.Click("32;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co' at 209;17.", repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01CoInfo, new RecordItemIndex(2));
            repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co.Click("209;17");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Auto' with focus on 'PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co'.", repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01CoInfo, new RecordItemIndex(3));
            repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co.PressKeys("Auto");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co1' at 43;17.", repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co1Info, new RecordItemIndex(4));
            repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co1.Click("43;17");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test' with focus on 'PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co1'.", repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co1Info, new RecordItemIndex(5));
            repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co1.PressKeys("Test");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(6));
            Mouse.ScrollWheel(-600);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co2' at 81;34.", repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co2Info, new RecordItemIndex(7));
            repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co2.Click("81;34");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co3'.", repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co3Info, new RecordItemIndex(8));
            Validate.Exists(repo.PlanitSoftwareTestingDigitalSolut.PLtCtl06PageplaceholderPLtCtl01Co3Info);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'PlanitContactPlanitTheLeadersIn.Client'.", repo.PlanitContactPlanitTheLeadersIn.ClientInfo, new RecordItemIndex(9));
            Host.Current.CloseApplication(repo.PlanitContactPlanitTheLeadersIn.Client, new Duration(0));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
